// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-mHUOxsJKJK-J-0OdKvX8HQobqDMyZM',
    appId: '1:287557824096:android:c0110f2e52e7541300dd05',
    messagingSenderId: '287557824096',
    projectId: 'fbfrutasmarcos',
    databaseURL: 'https://fbfrutasmarcos-default-rtdb.firebaseio.com',
    storageBucket: 'fbfrutasmarcos.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARgWXMyb-RiZQ06FY7_B197nEp6Yxljmg',
    appId: '1:287557824096:web:35324e57a391f56700dd05',
    messagingSenderId: '287557824096',
    projectId: 'fbfrutasmarcos',
    authDomain: 'fbfrutasmarcos.firebaseapp.com',
    databaseURL: 'https://fbfrutasmarcos-default-rtdb.firebaseio.com',
    storageBucket: 'fbfrutasmarcos.appspot.com',
  );
}
